// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dao

// Injectors from wire.go:

func initializeDao() (MongoBaseDao, error) {
	collection := NewProjectCollection()
	mongoBaseDao := NewBaseDao(collection)
	return mongoBaseDao, nil
}
