// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controllers

import (
	"dorapocket/dao"
	"dorapocket/service"
)

// Injectors from wire.go:

func initializeDao() (dao.MongoBaseDao, error) {
	collection := dao.NewProjectCollection()
	mongoBaseDao := dao.NewBaseDao(collection)
	return mongoBaseDao, nil
}

func initializePorjectService() service.ProjectService {
	collection := dao.NewProjectCollection()
	mongoBaseDao := dao.NewBaseDao(collection)
	projectService := service.NewProjectService(mongoBaseDao)
	return projectService
}
